openhab/openhab-docker

.gitignore
.travis.yml
Dockerfile
Makefile
README-short.txt
README.md
files/entrypoint.sh

Hi!
I started the Dockerfile based on the ubuntu image with java8 (as suggested in the forum).
The exposed volumes are /config and /userdata.
Please let me know if we can improve it anyhow.
Cheers
Hannes

New Dockerfile and update on Readme

---

README.md
files/entrypoint.sh

Hi!
I thought it might be interesting to access the console even when running the container as daemon in the background.
As the configuration is in the runtime folderfor now, I expect that there will be changes in the future how password and ssh-keys are going to be handled.
Cheers
Hannes

Add new command "console" to entrypoint.

---

Dockerfile

Devices passed into docker with --device tag get mounted with group guid 16 which does not have an entry in /etc/groups.  This change adds a "dockerdev" group with guid 16 and then adds the openhab user to that group.

Permissions fix to allow USB device passthrough

---

Dockerfile
files/entrypoint.sh

This should fix [#12](https://github.com/openhab/openhab-docker/issues/12). This is a new pull request instead of [#13](https://github.com/openhab/openhab-docker/pull/13). I merged the changes and tested them on Debian jessie with following docker compose file:
```
openhab2:
image: "openhab/usegosu"
net: host
volumes:
- "/etc/localtime:/etc/localtime:ro"
- "/etc/timezone:/etc/timezone:ro"
- "/opt/usegosu/userdata:/openhab/userdata"
- "/opt/usegosu/conf:/openhab/conf"
command: "server"
```
Signed-off-by: Christian Lehmann info@legacycode.org (github: legacycode)

[WIP] use gosu instead of sudo

---

README.md

I added a section to run the container with libpcap support. Added a table of contens and did a little bit rework on document.
@cniweb: Please close #41 after merge and update the Docu on Dockerhub, if possible :-) *cheers*

updated documentation. added libpcap support and table of content

---

1.8.3/amd64/Dockerfile
1.8.3/arm64/Dockerfile
1.8.3/armhf/Dockerfile
2.0.0/amd64/Dockerfile
2.0.0/arm64/Dockerfile
2.0.0/armhf/Dockerfile
2.1.0-snapshot/amd64/Dockerfile
2.1.0-snapshot/arm64/Dockerfile
2.1.0-snapshot/armhf/Dockerfile
update.sh

For the charting feature, the system, where OH2 is running, needs to
have some fonts installed. The package fontconfig should depend on all
needed packages on all systems (a shared library to access fonts and
some fonts (on debian libfreetype6 e.g.)).
I tested this on a amd64 Ubuntu host, however, it should work on armhf
and arm64 platforms, too.
Fixes #73
Signed-off-by: Florian Schmidt <florian.schmidt.welzow@t-online.de>

Install fontconfig for OH2 charts

---

README.md

We do not need manually copy the folders from the image to the mounted volume, because this is done by the entrypoint.sh script now. 
Since we have no other solution for libpcap and zwave support we need to run the container as root. This is done by overriding the command in the Dockerfile. Setting the -u parameter is useless, because we use gosu.

documentation rework

---

README.md

Add tty true to make sure the example is compatible with version 2.2 of openHAB 
Fixes #102 
See also https://community.openhab.org/t/oh2-2-docker-compose-vs-docker-does-not-start/34025/4

Add tty true for compatibility with the 2.2

---

README.md

Hi,
for me as a beginner it was not clear that the id for the host user "openhab" has to match the id of the docker container user "openhab". So I changed the readme to clarify this topic.
Thanks
Dominik

Clarify user configuration

---

README.md
entrypoint.sh

The uid and gid may not always be the same value. This patch allows the gid to be specified in the environment variable GROUP_ID. If a gid is not specified, the gid will fallback to being the same value as the uid. 
Signed-off-by: Tim Sedlmeyer <tim@sedlmeyer.org> (github: tssva)

Openhab GROUP_ID can now be set via variable at container creation time.

---

1.8.3/amd64/alpine/Dockerfile
1.8.3/amd64/alpine/entrypoint.sh
1.8.3/arm64/alpine/Dockerfile
1.8.3/arm64/alpine/entrypoint.sh
1.8.3/armhf/alpine/Dockerfile
1.8.3/armhf/alpine/entrypoint.sh
1.8.3/i386/alpine/Dockerfile
1.8.3/i386/alpine/entrypoint.sh
2.0.0/amd64/alpine/Dockerfile
2.0.0/arm64/alpine/Dockerfile
2.0.0/armhf/alpine/Dockerfile
2.0.0/i386/alpine/Dockerfile
2.1.0/amd64/alpine/Dockerfile
2.1.0/arm64/alpine/Dockerfile
2.1.0/armhf/alpine/Dockerfile
2.1.0/i386/alpine/Dockerfile
2.2.0-snapshot/amd64/alpine/Dockerfile
2.2.0-snapshot/arm64/alpine/Dockerfile
2.2.0-snapshot/armhf/alpine/Dockerfile
2.2.0-snapshot/i386/alpine/Dockerfile
update.sh

I've used the alpine image instead of the debian and all charts did
not work anymore. After finding:
https://github.com/docker-library/openjdk/issues/73
and installing the ttf.dejavu package manually, the charts worked again.
This commit adds this package to the alpine base packages which needs to
be installed to get a working OH2 environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/113)

Install ttf-dejavu for some basic fonts (needed for charts)

---

2.0.0/amd64/alpine/entrypoint.sh
2.0.0/arm64/alpine/entrypoint.sh
2.0.0/armhf/alpine/entrypoint.sh
2.0.0/i386/alpine/entrypoint.sh
2.1.0/amd64/alpine/entrypoint.sh
2.1.0/arm64/alpine/entrypoint.sh
2.1.0/armhf/alpine/entrypoint.sh
2.1.0/i386/alpine/entrypoint.sh
2.2.0-snapshot/amd64/alpine/entrypoint.sh
2.2.0-snapshot/arm64/alpine/entrypoint.sh
2.2.0-snapshot/armhf/alpine/entrypoint.sh
2.2.0-snapshot/i386/alpine/entrypoint.sh
entrypoint_alpine.sh
update.sh

In my OH2 installation, the instance.properties file is located in
the tmp directory, and not in the runtime directory, that's why the
deletion of the file does not succeed, and restarting the container
does not work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/114)

Delete different instance.properties path, too

---

README.md

Added a section to the README to descript what happens when a container detects the Image version of OH differs from the mapped in userdata folder's version.
Signed off by Richard Koshak rlkoshak@gmail.com
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/155)

Added an Upgrading section to the README

---

.travis.yml
README.md

* Update Travis build configuration
* Remove --tty option from run command because it is no longer required
* Remove `group: deprecated-2017Q2` because it is no longer a requirement for succesful builds
* Update README.md
* Update Table of Contents
* Document startup modes and how to configure a console logger in server mode
* Remove unnecessary backticks and spaces
* Remove tty configuration from commands/docker-compose examples because this option is no longer required
* Put each sentence on its own line which makes it easier for reviewing future changes
* Document how to build images for other architectures
* Add new lines before/after headers, lists and code blocks which fixes issues with some Markdown editors and renderers
---
This change is [<img …

Remove TTY from Travis config and README.md with some other improvements

---

1.8.3/amd64/alpine/Dockerfile
1.8.3/arm64/alpine/Dockerfile
1.8.3/armhf/alpine/Dockerfile
1.8.3/i386/alpine/Dockerfile
2.0.0/amd64/alpine/Dockerfile
2.0.0/arm64/alpine/Dockerfile
2.0.0/armhf/alpine/Dockerfile
2.0.0/i386/alpine/Dockerfile
2.1.0/amd64/alpine/Dockerfile
2.1.0/arm64/alpine/Dockerfile
2.1.0/armhf/alpine/Dockerfile
2.1.0/i386/alpine/Dockerfile
2.2.0/amd64/alpine/Dockerfile
2.2.0/arm64/alpine/Dockerfile
2.2.0/armhf/alpine/Dockerfile
2.2.0/i386/alpine/Dockerfile
2.3.0/amd64/alpine/Dockerfile
2.3.0/arm64/alpine/Dockerfile
2.3.0/armhf/alpine/Dockerfile
2.3.0/i386/alpine/Dockerfile
2.4.0-snapshot/amd64/alpine/Dockerfile
2.4.0-snapshot/arm64/alpine/Dockerfile
2.4.0-snapshot/armhf/alpine/Dockerfile
2.4.0-snapshot/i386/alpine/Dockerfile
README.md
update.sh

Upgrades the Alpine images to v3.8 which was released yesterday.
See also: https://alpinelinux.org/posts/Alpine-3.8.0-released.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/183)

Upgrade to Alpine v3.8

---

.travis.yml

The e-mail option was already deprecated for some time but it seems to have been removed from the command now causing the login to fail.
See also: https://docs.docker.com/engine/deprecated/#-e-and---email-flags-on-docker-login
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/188)

Fix #187 by removing legacy e-mail option from docker login

---

README.md

I spent some time last night wondering why my rules execute in UTC time instead of local time. Then I found the solution, and it would be nice if you could add the info on the README, as it already instructs how to set system time. Which is not enough to set it for Java. So perhaps this line could be addded:
-e "EXTRA_JAVA_OPTS=-Duser.timezone=Europe/YourTZCity" \
Which then sets the Java to run in correct timezone, and rules work in correct times along with properly timed logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/185)

correct timezone for containers

---

contrib/cont-init.d/20-open-ssh-server

Fixes the broken link in the [Open access from external hosts](https://github.com/openhab/openhab-docker#open-access-from-external-hosts) README section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/214)

Fix broken 20-open-ssh-server link in README

---

1.8.3/alpine/entrypoint.sh
1.8.3/debian/entrypoint.sh
2.0.0/alpine/entrypoint.sh
2.0.0/debian/entrypoint.sh
2.1.0/alpine/entrypoint.sh
2.1.0/debian/entrypoint.sh
2.2.0/alpine/entrypoint.sh
2.2.0/debian/entrypoint.sh
2.3.0/alpine/entrypoint.sh
2.3.0/debian/entrypoint.sh
2.4.0/alpine/entrypoint.sh
2.4.0/debian/entrypoint.sh
2.5.0-snapshot/alpine/entrypoint.sh
2.5.0-snapshot/debian/entrypoint.sh
README.md
entrypoint-alpine.sh
entrypoint-debian.sh

Using the `--user` option results in permission issues nowdays so it should be removed.
Added some other known addons requiring unlimited crypto.
Fixes #220 
Fixes #221
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/222)

Update user/group ID and unlimited crypto documentation

---

1.8.3/alpine/entrypoint.sh
1.8.3/debian/entrypoint.sh
2.0.0/alpine/entrypoint.sh
2.0.0/debian/entrypoint.sh
2.1.0/alpine/entrypoint.sh
2.1.0/debian/entrypoint.sh
2.2.0/alpine/entrypoint.sh
2.2.0/debian/entrypoint.sh
2.3.0/alpine/entrypoint.sh
2.3.0/debian/entrypoint.sh
2.4.0/alpine/entrypoint.sh
2.4.0/debian/entrypoint.sh
2.5.0-snapshot/alpine/entrypoint.sh
2.5.0-snapshot/debian/entrypoint.sh
2.5.0.M1/alpine/entrypoint.sh
2.5.0.M1/debian/entrypoint.sh
README.md
entrypoint-alpine.sh
entrypoint-debian.sh

Run the continuation scripts after the first chown so users can run setpcap on the java binary.
See https://community.openhab.org/t/cannot-configure-openhab-docker-to-use-port-80/67376/8?u=hakan
Signed-off-by: Hakan Tandogan <hakan@tandogan.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/227)

Allow for root operations in continuation scripts

---

1.8.3/alpine/Dockerfile-amd64
1.8.3/alpine/Dockerfile-arm64
1.8.3/alpine/Dockerfile-armhf
2.0.0/alpine/Dockerfile-amd64
2.0.0/alpine/Dockerfile-arm64
2.0.0/alpine/Dockerfile-armhf
2.1.0/alpine/Dockerfile-amd64
2.1.0/alpine/Dockerfile-arm64
2.1.0/alpine/Dockerfile-armhf
2.2.0/alpine/Dockerfile-amd64
2.2.0/alpine/Dockerfile-arm64
2.2.0/alpine/Dockerfile-armhf
2.3.0/alpine/Dockerfile-amd64
2.3.0/alpine/Dockerfile-arm64
2.3.0/alpine/Dockerfile-armhf
2.4.0/alpine/Dockerfile-amd64
2.4.0/alpine/Dockerfile-arm64
2.4.0/alpine/Dockerfile-armhf
2.5.0-snapshot/alpine/Dockerfile-amd64
2.5.0-snapshot/alpine/Dockerfile-arm64
2.5.0-snapshot/alpine/Dockerfile-armhf
2.5.0.M1/alpine/Dockerfile-amd64
2.5.0.M1/alpine/Dockerfile-arm64
2.5.0.M1/alpine/Dockerfile-armhf
update-docker-files.sh

The image fails to start with "java.io.FileNotFoundException: /usr/lib/libnss3.so"
See https://github.com/docker-library/openjdk/issues/289
Signed-off-by: Hakan Tandogan <hakan@tandogan.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/230)

Install missing libnss

---

README.md

The containers should also work on Windows and macOS when ports mappings are used instead of using the host networking driver. 
See [community topic](https://community.openhab.org/t/openhab-in-linux-container-on-windows-docker-wont-start/79701?u=wborn).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/241)

Add Windows and macOS documentation

---

.travis.yml
update-travis-config.sh

These warnings showed in:
https://travis-ci.org/openhab/openhab-docker/builds/648174791/config?utm_medium=notification&utm_source=github_status
You can also see them when pasting the .travis.yml contents in https://config.travis-ci.com/explore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/277)

Fix Travis build config validation warnings

---

README.md
contrib/cont-init.d/10-show-directories
contrib/cont-init.d/20-add-allowed-ssh-keys
contrib/cont-init.d/20-open-ssh-server
contrib/cont-init.d/20-set-host-key
contrib/cont-init.d/40-openhabcloud
contrib/cont-init.d/50-setpcap-on-java

* Use https in all URLs
* Use absolute URL for openHAB logo to simplify publishing to Docker Hub
* Fix broken link to missing 50-setpcap-on-java and fix wrong Java location by using JAVA_HOME
* Use enviroment variables in example scripts
* Add Loxone binding to list of add-ons that require unlimited crypto
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/283)

Improve documentation and contrib scripts

---

.travis.yml
README.md
update-functions.sh
update-readme.sh
update-travis-config.sh

Docker Hub silently ignores Readme content exceeding 25k chars. It doesn't give any error message and keeps showing the old Readme contents as if it was never updated at all. :disappointed: 
See also: https://github.com/docker/hub-feedback/issues/238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/291)

Make sure README.md does not exceed 25k char limit of Docker Hub

---

2.5.8-snapshot/alpine/Dockerfile
2.5.8-snapshot/debian/Dockerfile
3.0.0-snapshot/alpine/Dockerfile
3.0.0-snapshot/debian/Dockerfile
update-docker-files.sh

The connections to ci.openhab.org are no longer blocked in the Travis CI infrastructure.
Fixes #297
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/303)

Undo Travis CI SNAPSHOT download workaround

---

helper-functions

There won't be any 3.0.x-snapshot builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/341)

Update snapshot version logic

---

alpine/Dockerfile
debian/Dockerfile

Hello, I hope this is wanted. I haven't found any reference to health checks in the repo nor in the openhab discussion forum. I did find one compose file that implemented the healthcheck with the docker run command. But I though it's best to directly implement it in the official dockerfiles. I successfully tested the debian version on a raspberry pi.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/351)

Added healthcheck in alpine and debian dockerfile

---

README.md
alpine/Dockerfile
alpine/entrypoint
debian/Dockerfile
debian/entrypoint

Allows for customizing the shell options used by the entrypoint script.
E.g. set it to `+x` to disable the trace logging or set it to `-v` to also print shell input lines.
Fixes #346

Add EXTRA_SHELL_OPTS environment variable

---

alpine/update
debian/update

It was using the artifacts produced by the wrong Jenkins jobs.
Also removes the logic for updating the legacy add-ons KAR which no longer exists in OH3.

Fix SNAPSHOT KAR update

---

.github/workflows/build-images.yml
README.md
alpine/Dockerfile
debian/Dockerfile
helper-functions

Updates:
* Alpine to 3.14.3
* Debian to 11.1
* binfmt to tonistiigi/binfmt:qemu-v6.1.0 (required for building Debian 11 ARM images with buildx)
Furthermore the [pushrm](https://github.com/christian-korneck/docker-pushrm) Docker CLI plugin is now used for updating the README on Docker Hub.

Upgrade base images and build tools

---

debian/Dockerfile

It only adds 50 kB to the image and ping is also supported in the Alpine image.
Fixes #374

Add iputils-ping to Debian image

---

README.md

Compose v2 is a Docker CLI command which is a drop in replacement so the dash is no longer used.

Use Docker Compose v2 syntax in README.md

---

README.md

Most users use OH3, so don't first bother them with how this was done in OH2.

Explain how to setup console logger in OH3 before OH2

---

README.md
alpine/Dockerfile
alpine/entrypoint
alpine/update
debian/Dockerfile
debian/entrypoint
debian/update

The Temurin JDK is easier to install because it supports all architectures using an APT repo.
It is also more open source compared to the Zulu JDK, for building it yourself, see: https://github.com/adoptium/temurin-build
With these changes the JAVA_HOME, JAVA_VERSION, OPENHAB_VERSION environment variables are no longer exposed/used to prevent upgrade issues when the container is managed by UIs that persist all env default values like Portainer.
Closes #393

Replace Zulu with Temurin JDK and prevent env var issues

---

debian/entrypoint

For some reason p11-kit cannot find any modules during the linux/arm/v7 build.
As a result there would be no usable certificates causing all HTTPS connections to fail.
See: [Error: Unable to execute HTTP request: after upgrade from 3.2.0 to 3.3.0 M7](https://community.openhab.org/t/error-unable-to-execute-http-request-after-upgrade-from-3-2-0-to-3-3-0-m7/136834?u=wborn)

Make sure Adoptium cacerts are always populated

---

alpine/Dockerfile

Addresses CVE-2022-37434, see:
https://security.alpinelinux.org/vuln/CVE-2022-37434

Upgrade to Alpine 3.16.2

---

README.md
debian/Dockerfile
debian/entrypoint

* Replace Temurin with OpenJDK from Debian repos which does not crash when using arm64 image on the Raspberry Pi 3
* Switch back to Debian 11 which consumes less memory
Fixes #416
Reverts #422

Fix JVM crashes and insufficient memory issues

---

contrib/cont-init.d/20-add-console-loggers

This script automatically adds the console loggers when they have not yet been configured (see [server mode](https://github.com/openhab/openhab-docker#server-mode)).

Add script for automatically adding console loggers

---

helper-functions

On old Docker versions pulling an image would fail with "missing signature key". By default buildx creates manifests having the newer OCI media type which is unsupported by older Docker versions.
To inspect the media type in a manifest run: docker manifest inspect openhab/openhab
See:
* https://community.openhab.org/t/containerstation-4-0-0-m3-last-working-build/149063
* https://community.openhab.org/t/error-missing-signature-key-for-oh-4-0-2-docker-image/149154

Make manifests compatible with older Docker versions

---

helper-functions

The POMs got reformatted with openhab/openhab-distro#1627.

Fix SNAPSHOT version logic

---

.github/workflows/build-images.yml
.github/workflows/validate-readme.yml

This fixes the following deprecation warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20

Upgrade GHA dependencies

---

README.md
debian/Dockerfile

Regular security support has ended for Debian 11.
See: https://www.debian.org/News/2024/20240814

Upgrade to Debian 12.7

---

README.md

The version property was used by Docker Compose CLI V1 which has been EOL since mid 2023.
If you use it with Docker Compose CLI V2 the following warnings are logged:
> the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
See: https://docs.docker.com/reference/compose-file/version-and-name/#version-top-level-element-obsolete

Remove obsolete version property from Docker Compose examples

---

README.md
alpine/Dockerfile
alpine/entrypoint
build
debian/Dockerfile
debian/entrypoint
helper-functions

* Use Java 21 with openHAB 5
* Remove linux/arm/v7 support
* Update versions in build help
* Install Temurin when Debian does not have an installation package in its repositories for an OpenJDK version
Related to openhab/openhab-distro#1689

Add openHAB 5 support

---

alpine/Dockerfile

Add workaround for broken `/var/lock` symlink in Alpine 3.21 image

---

alpine/Dockerfile
debian/Dockerfile

Upgrade from Debian 12.8 to Debian 12.9, released 11-Jan-2025.
I added `apt upgrade` to the Debian script, which should upgrade installed packages. This will basically also upgrade to next 12.x releases once published, as base-files etc. will be upgraded.
WDYT?

Upgrade packages during image creation

---

alpine/Dockerfile

See https://github.com/openhab/openhab-distro/issues/1693#issuecomment-2569575296.

Alpine image: Install NodeJS for Matter binding

---

debian/Dockerfile
debian/entrypoint

This will use su-exec instead of gosu similar to the Alpine images. As a result the golang dependency is removed which prevents potential vulnerabilities.
Fixes #458

Replace gosu with su-exec in Debian images

---

debian/Dockerfile
helper-functions

Debian 13 has no OpenJDK 17 packages and Temurin 17 does not install on Debian 13 as it depends on libasound2 which is missing on armhf.

Use Debian 12 with openHAB 4
