files/entrypoint.sh

Signed-off-by: Hannes Schaller <admin@cyberkov.at>

update entrypoint to properly initialize /openhab/config. fixes #5

---

Dockerfile

This should fix #5 
Cheers
Hannes

Fix CMD command to use brackets.

---

Dockerfile

Gives access via the GPIO group on RPI. Was kinda useful for me. Take it or leave it :)

Allow access to GPIO pins from the container on RPI

---

README.md
files/entrypoint.sh

Fix for #36
Needed for: openhab/openhab-distro#318
Signed-off-by: Christian Häussler <c-n-i@web.de> (github: cniweb)

Updating paths for new OH2 folder layout

---

Dockerfile
Makefile

https://github.com/openhab/openhab-distro/pull/369
Signed-off-by: Christian Häussler <c-n-i@web.de> (github: @cniweb)

Change download URL

---

Dockerfile

See https://github.com/tianon/gosu/issues/19
Signed-off-by: Christian Häussler <c-n-i@web.de> (github: @cniweb)

Update GOSU to version 1.10

---

.travis.yml
Makefile
README.md

I removed the FLAVOR from Makefile and .travis.yml. There are three builds now. I did some rework on the readme.md as well. This will resolve #44.
Signed-off-by: Christian Lehmann info@legacycode.org (github: legacycode)

removed flavor and rework on readme.md

---

README.md

I think using docker named container as a starting point for beginner is easier to handle than using mounted volumes. with named container the data still persist and there is no need to deal with file system permissions and chown 9001. pls review.

starting docker using named data container. easier for beginners.

---

1.8.3/amd64/Dockerfile
1.8.3/amd64/entrypoint.sh
1.8.3/arm64/Dockerfile
1.8.3/arm64/entrypoint.sh
1.8.3/armhf/Dockerfile
1.8.3/armhf/entrypoint.sh
2.0.0/amd64/Dockerfile
2.0.0/amd64/entrypoint.sh
2.0.0/arm64/Dockerfile
2.0.0/arm64/entrypoint.sh
2.0.0/armhf/Dockerfile
2.0.0/armhf/entrypoint.sh
2.1.0-snapshot/amd64/Dockerfile
2.1.0-snapshot/amd64/entrypoint.sh
2.1.0-snapshot/arm64/Dockerfile
2.1.0-snapshot/arm64/entrypoint.sh
2.1.0-snapshot/armhf/Dockerfile
2.1.0-snapshot/armhf/entrypoint.sh
entrypoint.sh
update.sh

I added the entrypoint script again and fixed the run as user_id problem.

Added entrypoint and gosu

---

1.8.3/amd64/alpine/Dockerfile
1.8.3/arm64/alpine/Dockerfile
1.8.3/armhf/alpine/Dockerfile
1.8.3/i386/alpine/Dockerfile
2.0.0/amd64/alpine/Dockerfile
2.0.0/arm64/alpine/Dockerfile
2.0.0/armhf/alpine/Dockerfile
2.0.0/i386/alpine/Dockerfile
2.1.0/amd64/alpine/Dockerfile
2.1.0/arm64/alpine/Dockerfile
2.1.0/armhf/alpine/Dockerfile
2.1.0/i386/alpine/Dockerfile
2.2.0-snapshot/amd64/alpine/Dockerfile
2.2.0-snapshot/arm64/alpine/Dockerfile
2.2.0-snapshot/armhf/alpine/Dockerfile
2.2.0-snapshot/i386/alpine/Dockerfile
update.sh

Fixes #122
Signed-off-by: Christian Häussler <c-n-i@web.de>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/123)

Install ttf-dejavu for some basic fonts (needed for charts)

---

README.md

Signed-off-by: Christian Häussler <c-n-i@web.de>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/124)

Change openHAB2 naming to openHAB

---

1.8.3/amd64/alpine/Dockerfile
1.8.3/arm64/alpine/Dockerfile
1.8.3/armhf/alpine/Dockerfile
1.8.3/i386/alpine/Dockerfile
2.0.0/amd64/alpine/Dockerfile
2.0.0/arm64/alpine/Dockerfile
2.0.0/armhf/alpine/Dockerfile
2.0.0/i386/alpine/Dockerfile
2.1.0/amd64/alpine/Dockerfile
2.1.0/arm64/alpine/Dockerfile
2.1.0/armhf/alpine/Dockerfile
2.1.0/i386/alpine/Dockerfile
2.2.0/amd64/alpine/Dockerfile
2.2.0/arm64/alpine/Dockerfile
2.2.0/armhf/alpine/Dockerfile
2.2.0/i386/alpine/Dockerfile
2.3.0-snapshot/amd64/alpine/Dockerfile
2.3.0-snapshot/arm64/alpine/Dockerfile
2.3.0-snapshot/armhf/alpine/Dockerfile
2.3.0-snapshot/i386/alpine/Dockerfile
README.md
update.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/131)

 Switch back to alpine v3.6

---

1.8.3/amd64/alpine/Dockerfile
1.8.3/arm64/alpine/Dockerfile
1.8.3/armhf/alpine/Dockerfile
1.8.3/i386/alpine/Dockerfile
2.0.0/amd64/alpine/Dockerfile
2.0.0/arm64/alpine/Dockerfile
2.0.0/armhf/alpine/Dockerfile
2.0.0/i386/alpine/Dockerfile
2.1.0/amd64/alpine/Dockerfile
2.1.0/arm64/alpine/Dockerfile
2.1.0/armhf/alpine/Dockerfile
2.1.0/i386/alpine/Dockerfile
2.2.0/amd64/alpine/Dockerfile
2.2.0/arm64/alpine/Dockerfile
2.2.0/armhf/alpine/Dockerfile
2.2.0/i386/alpine/Dockerfile
2.3.0-snapshot/amd64/alpine/Dockerfile
2.3.0-snapshot/arm64/alpine/Dockerfile
2.3.0-snapshot/armhf/alpine/Dockerfile
2.3.0-snapshot/i386/alpine/Dockerfile
README.md
update.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/134)

Alpine 3.7

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/145)

changed config option 'net' to 'network_mode'

---

README.md

Fixes #150
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/151)

Added /debian into broken links

---

README.md

Ansible is more and more used to automatise server setups. I control all my boxes with it, and thought I might as well contribute my playbook running OpenHAB container with it. It could be enhanced to role, but this serves basic openhab run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/186)

Provide example playbook for Ansible in README

---

README.md

added missing chars and added extra docker-compose.yml example for use for docker volumes instead of local directories
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/191)

Update README.md to fix Issue #190

---

1.8.3/amd64/alpine/entrypoint.sh
1.8.3/arm64/alpine/entrypoint.sh
1.8.3/armhf/alpine/entrypoint.sh
2.0.0/amd64/alpine/entrypoint.sh
2.0.0/arm64/alpine/entrypoint.sh
2.0.0/armhf/alpine/entrypoint.sh
2.1.0/amd64/alpine/entrypoint.sh
2.1.0/arm64/alpine/entrypoint.sh
2.1.0/armhf/alpine/entrypoint.sh
2.2.0/amd64/alpine/entrypoint.sh
2.2.0/arm64/alpine/entrypoint.sh
2.2.0/armhf/alpine/entrypoint.sh
2.3.0/amd64/alpine/entrypoint.sh
2.3.0/arm64/alpine/entrypoint.sh
2.3.0/armhf/alpine/entrypoint.sh
2.4.0-snapshot/amd64/alpine/entrypoint.sh
2.4.0-snapshot/arm64/alpine/entrypoint.sh
2.4.0-snapshot/armhf/alpine/entrypoint.sh
2.4.0.M3/amd64/alpine/entrypoint.sh
2.4.0.M3/arm64/alpine/entrypoint.sh
2.4.0.M3/armhf/alpine/entrypoint.sh
2.4.0.M4/amd64/alpine/entrypoint.sh
2.4.0.M4/arm64/alpine/entrypoint.sh
2.4.0.M4/armhf/alpine/entrypoint.sh
2.4.0.M5/amd64/alpine/entrypoint.sh
2.4.0.M5/arm64/alpine/entrypoint.sh
2.4.0.M5/armhf/alpine/entrypoint.sh
entrypoint-alpine.sh

Fixes #202
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/204)

Fix Alpine containers not starting when using unlimited cryptographic strength policy

---

README.md
contrib/cont-init.d/10-show-directories
contrib/cont-init.d/20-add-allowed-ssh-keys
contrib/cont-init.d/20-set-host-key

Explaining the use cases for the continuation scripts...
Signed-off-by: Hakan Tandogan <hakan@tandogan.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/206)

Documentation and examples for the s6 init continuation scripts

---

1.8.3/alpine/entrypoint.sh
1.8.3/debian/entrypoint.sh
2.0.0/alpine/entrypoint.sh
2.0.0/debian/entrypoint.sh
2.1.0/alpine/entrypoint.sh
2.1.0/debian/entrypoint.sh
2.2.0/alpine/entrypoint.sh
2.2.0/debian/entrypoint.sh
2.3.0/alpine/entrypoint.sh
2.3.0/debian/entrypoint.sh
2.4.0/alpine/entrypoint.sh
2.4.0/alpine/manifest.yml
2.4.0/debian/entrypoint.sh
2.4.0/debian/manifest.yml
2.5.0-snapshot/alpine/entrypoint.sh
2.5.0-snapshot/debian/entrypoint.sh
2.5.0-snapshot/debian/manifest.yml
README.md
entrypoint-alpine.sh
entrypoint-debian.sh
project-orga/MAINTAINERS.md
update-docker-files.sh

These quotes, spaces and typo fixes should make Feram a bit more happy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/219)

Feram fixes

---

1.8.3/alpine/Dockerfile-amd64
1.8.3/alpine/Dockerfile-arm64
1.8.3/alpine/Dockerfile-armhf
2.0.0/alpine/Dockerfile-amd64
2.0.0/alpine/Dockerfile-arm64
2.0.0/alpine/Dockerfile-armhf
2.1.0/alpine/Dockerfile-amd64
2.1.0/alpine/Dockerfile-arm64
2.1.0/alpine/Dockerfile-armhf
2.2.0/alpine/Dockerfile-amd64
2.2.0/alpine/Dockerfile-arm64
2.2.0/alpine/Dockerfile-armhf
2.3.0/alpine/Dockerfile-amd64
2.3.0/alpine/Dockerfile-arm64
2.3.0/alpine/Dockerfile-armhf
2.4.0/alpine/Dockerfile-amd64
2.4.0/alpine/Dockerfile-arm64
2.4.0/alpine/Dockerfile-armhf
2.5.0-snapshot/alpine/Dockerfile-amd64
2.5.0-snapshot/alpine/Dockerfile-arm64
2.5.0-snapshot/alpine/Dockerfile-armhf
2.5.0.M1/alpine/Dockerfile-amd64
2.5.0.M1/alpine/Dockerfile-arm64
2.5.0.M1/alpine/Dockerfile-armhf
update-docker-files.sh

Updates the Alpine containers to v3.9. 
See also the [Alpine v3.9 release announcement](https://alpinelinux.org/posts/Alpine-3.9.0-released.html).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/228)

Update to Alpine v3.9

---

README.md

* Updates the documentation for the Alpine 3.9 upgrade
* Fix capitalization of Alpine, Debian, Docker, Java
* Fix typos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/231)

Update Alpine to 3.9 in README and some minor improvements

---

1.8.3/alpine/Dockerfile-amd64
1.8.3/alpine/Dockerfile-arm64
1.8.3/alpine/Dockerfile-armhf
2.0.0/alpine/Dockerfile-amd64
2.0.0/alpine/Dockerfile-arm64
2.0.0/alpine/Dockerfile-armhf
2.1.0/alpine/Dockerfile-amd64
2.1.0/alpine/Dockerfile-arm64
2.1.0/alpine/Dockerfile-armhf
2.2.0/alpine/Dockerfile-amd64
2.2.0/alpine/Dockerfile-arm64
2.2.0/alpine/Dockerfile-armhf
2.3.0/alpine/Dockerfile-amd64
2.3.0/alpine/Dockerfile-arm64
2.3.0/alpine/Dockerfile-armhf
2.4.0/alpine/Dockerfile-amd64
2.4.0/alpine/Dockerfile-arm64
2.4.0/alpine/Dockerfile-armhf
2.5.0-snapshot/alpine/Dockerfile-amd64
2.5.0-snapshot/alpine/Dockerfile-arm64
2.5.0-snapshot/alpine/Dockerfile-armhf
2.5.0.M1/alpine/Dockerfile-amd64
2.5.0.M1/alpine/Dockerfile-arm64
2.5.0.M1/alpine/Dockerfile-armhf
README.md
update-docker-files.sh

See release announcements:
* [Alpine 3.10.0](https://alpinelinux.org/posts/Alpine-3.10.0-released.html)
* [Alpine 3.10.1](https://alpinelinux.org/posts/Alpine-3.10.1-released.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/238)

Update Alpine images to v3.10

---

README.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/242)

Fix documentation hierarchy

---

1.8.3/alpine/manifest.yml
1.8.3/debian/manifest.yml
2.0.0/alpine/manifest.yml
2.0.0/debian/manifest.yml
2.1.0/alpine/manifest.yml
2.1.0/debian/manifest.yml
2.2.0/alpine/manifest.yml
2.2.0/debian/manifest.yml
2.3.0/alpine/manifest.yml
2.3.0/debian/manifest.yml
2.4.0/alpine/manifest.yml
2.4.0/debian/manifest.yml
2.5.0/alpine/manifest.yml
2.5.0/debian/manifest.yml
2.5.1/alpine/manifest.yml
2.5.1/debian/manifest.yml
2.5.2-snapshot/alpine/manifest.yml
2.5.2-snapshot/debian/manifest.yml
3.0.0-snapshot/alpine/manifest.yml
3.0.0-snapshot/debian/manifest.yml
update-docker-files.sh

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/279)

Fix missing version-distro tags

---

README.md

Fixes #267
Fixes #270
Fixes #275
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/289)

Add "Common Problems" section to README.md

---

.travis.yml
update-travis-config.sh

Upgrades the Travis CI environment to use:
* Ubuntu 20.04
* Docker 19.03.12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/307)

Upgrade build environment

---

2.3.0/debian/Dockerfile
2.4.0/debian/Dockerfile
2.5.6/debian/Dockerfile
2.5.7/debian/Dockerfile
2.5.8/debian/Dockerfile
2.5.9-snapshot/debian/Dockerfile
3.0.0-snapshot/debian/Dockerfile
update-docker-files.sh

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/308)

Upgrade to Debian 10.5, Zulu JDK 8.0.265/11.0.8

---

2.3.0/alpine/Dockerfile
2.3.0/debian/Dockerfile
2.4.0/alpine/Dockerfile
2.4.0/debian/Dockerfile
2.5.10/alpine/Dockerfile
2.5.10/debian/Dockerfile
2.5.11-snapshot/alpine/Dockerfile
2.5.11-snapshot/debian/Dockerfile
2.5.8/alpine/Dockerfile
2.5.8/debian/Dockerfile
2.5.9/alpine/Dockerfile
2.5.9/debian/Dockerfile
3.0.0-snapshot/alpine/Dockerfile
3.0.0-snapshot/debian/Dockerfile
3.0.0.M3/alpine/Dockerfile
3.0.0.M3/debian/Dockerfile
3.0.0.M4/alpine/Dockerfile
3.0.0.M4/debian/Dockerfile
3.0.0.M5/alpine/Dockerfile
3.0.0.M5/debian/Dockerfile
update-docker-files.sh

Upgrade base images to:
* Debian 10.7-slim
* Alpine 3.12.2
Upgrade Zulu JDK versions to:
* 8.0.275
* 11.0.9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/323)

Upgrade base images and Zulu JDK

---

openhab-update.sh

* Fix DEFAULT command not properly restoring default files
* Create directories before moving files with MOVE command
* Run commands only when file/directory exists
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/327)

Improve update commands

---

2.3.0/alpine/update.sh
2.3.0/debian/update.sh
2.4.0/alpine/update.sh
2.4.0/debian/update.sh
2.5.10/alpine/update.sh
2.5.10/debian/update.sh
2.5.11/alpine/update.sh
2.5.11/debian/update.sh
2.5.12-snapshot/alpine/update.sh
2.5.12-snapshot/debian/update.sh
2.5.9/alpine/update.sh
2.5.9/debian/update.sh
3.0.0-snapshot/alpine/update.sh
3.0.0-snapshot/debian/update.sh
3.0.0.M4/alpine/update.sh
3.0.0.M4/debian/update.sh
3.0.0.M5/alpine/update.sh
3.0.0.M5/debian/update.sh
3.0.0.RC1/alpine/update.sh
3.0.0.RC1/debian/update.sh

Applies #327
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/328)

Apply update script changes

---

README.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/329)

Add OH3 console logger configuration to README.md

---

.github/workflows/build-images.yml
.github/workflows/validate-readme.yml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/337)

Fix GA workflow branches

---

helper-functions

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/339)

Automatically discover available SNAPSHOT versions

---

.github/workflows/build-images.yml
.github/workflows/validate-readme.yml
README.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/342)

Update workflow and documentation for renamed branch

---

helper-functions

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/345)

Remove openhab-distro master branch from available snapshot versions

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation_issue.md
.github/ISSUE_TEMPLATE/feature_request.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/347)

Add issue templates

---

README.md
alpine/Dockerfile
debian/Dockerfile

Updates:
* Zulu JDKs to 8.0.282, 11.0.10
* Alpine to 3.13.1
* Debian to 10.8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/352)

Upgrade Zulu JDKs and base images

---

debian/Dockerfile

Fixes #350
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openhab/openhab-docker/354)

Fix TLS root CA certificates problem

---

alpine/Dockerfile
alpine/update
debian/Dockerfile
debian/update

Related to openhab/openhab-distro#1256

Download milestones and releases using openHAB redirect

---

alpine/entrypoint
debian/entrypoint

Use s6 style init only when s6 is not installed

---

alpine/Dockerfile
alpine/entrypoint
build
debian/Dockerfile
debian/entrypoint
helper-functions

Remove OH2 support from build scripts

---

README.md
alpine/Dockerfile
debian/Dockerfile

Updates:
* Zulu JDK to 11.0.12
* Alpine to 3.14.2
* Debian to 10.10

Upgrade Zulu JDK and base images

---

debian/Dockerfile

Updates the Zulu JDK to 11.0.13

Upgrade Zulu JDK

---

README.md

Add monotonic clock problem

---

README.md
alpine/Dockerfile

Upgrade to Alpine 3.15.0

---

debian/Dockerfile

Upgrade to Debian 11.2

---

debian/Dockerfile

Upgrade to Zulu JDK 11.0.14

---

helper-functions

See: https://github.blog/2021-09-01-improving-git-protocol-security-github/

Switch to secured protocol to fix build

---

alpine/Dockerfile
alpine/entrypoint

* Add eudev for accessing device information
* Add gcompat for GNU C library compatibilty
* Change /var/lock permissions for writing nrjavaserial lock files
Fixes #144
Fixes #170

Fix some Alpine compatibility issues

---

alpine/Dockerfile

Upgrade to Alpine 3.15.4

---

debian/Dockerfile

* Upgrade to Zulu JDK 11.0.15
* Add Zulu JDK 17.0.3 URLs
* Use `arch` to determine architecture

Upgrade to Zulu JDK 11.0.15 and add Zulu JDK 17.0.3 URLs

---

README.md
alpine/entrypoint
debian/entrypoint

Set capabilities when available for add-ons using Pcap4J

---

README.md
alpine/Dockerfile

Upgrade to Alpine 3.16.0

---

.github/workflows/build-images.yml
.github/workflows/validate-readme.yml
helper-functions

Upgrade binfmt and GHA actions

---

alpine/Dockerfile
debian/Dockerfile

* Alpine to 3.16.1
* Debian to 11.4

Upgrade base images

---

alpine/entrypoint
debian/entrypoint

Add openhab user to audio group

---

alpine/entrypoint
debian/entrypoint

See also: https://github.com/openhab/openhab-docker/issues/3#issuecomment-226383958

Improve host distro group compatibility

---

debian/Dockerfile

See: https://www.debian.org/News/2022/2022091002

Upgrade to Debian 11.5

---

README.md
alpine/Dockerfile

See: https://www.alpinelinux.org/posts/Alpine-3.17.0-released.html

Upgrade to Alpine 3.17

---

.github/workflows/build-images.yml
helper-functions

Upgrade binfmt and GHA Ubuntu

---

README.md
alpine/Dockerfile
alpine/update
debian/Dockerfile
debian/update
helper-functions

Related to openhab/openhab-core#2994

Use Java 17 with openHAB 4

---

debian/Dockerfile

See: https://www.debian.org/News/2022/20221217

Upgrade to Debian 11.6

---

alpine/update
debian/update

Similar to openhab/openhab-distro#1532

Automatically run upgrade tool

---

README.md
debian/Dockerfile

See: https://www.debian.org/News/2023/20230610

Upgrade to Debian 12.0

---

contrib/cont-init.d/30-jetty-increase-webclients

Example script in docker startup, depends on https://github.com/openhab/openhab-distro/pull/1576

Example script to increase webclient threads

---

debian/Dockerfile

See: https://www.debian.org/News/2023/2023100702

Upgrade to Debian 11.8

---

alpine/Dockerfile
debian/Dockerfile

Migrate to org.opencontainers.* labels

---

README.md
alpine/Dockerfile

See: https://www.alpinelinux.org/posts/Alpine-3.19.0-released.html

Upgrade to Alpine 3.19

---

alpine/update
debian/update

Related to https://github.com/openhab/openhab-core/pull/4019

Clear marketplace cache during upgrade

---

debian/Dockerfile

See: https://www.debian.org/News/2024/2024021002

Upgrade to Debian 11.9

---

debian/Dockerfile

See: https://www.debian.org/News/2024/20241109

Upgrade to Debian 12.8

---

README.md
alpine/Dockerfile

See:
* https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.21.0
* https://alpinelinux.org/posts/Alpine-3.21.0-released.html

Upgrade to Alpine 3.21

---

.github/workflows/build-images.yml
README.md
helper-functions

* Upgrade binfmt to 8.1.5
* Use Ubuntu 24.04 with GHA

Tooling upgrades

---

README.md
alpine/Dockerfile

See:
* https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.22.0
* https://www.alpinelinux.org/posts/Alpine-3.22.0-released.html

Upgrade to Alpine 3.22
